### ISSUE TITLE
Check models that fail as actuator model has been updated

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#4002]
The new actuator model (https://github.com/lbl-srg/modelica-buildings/pull/4000) causes some models to fail to simulate, see `conf.yml` in 
https://github.com/lbl-srg/modelica-buildings/pull/4000/files#diff-27f3a54beb1453b97cf6c7dfd9fa86b042c9c7e332cd38ca55ea859c936120a8

This issue is to see if there is something that need to be improved in these models.

**Comment by mwetter** [comment]
@AntoineGautier : Could you please have a look into why these models fail with the new actuator model. These are from the HP template and the hydronic configurations. I believe the hydronic configuration have a pump that works against a fully closed valve.
I am not sure why `Buildings.Templates.Plants.HeatPumps.Components.Validation.ValvesIsolation` fails with OCT, but at the time of when OCT stalls, there is a discontinuity in slope:

![image](https://github.com/user-attachments/assets/624c9d30-db65-4c5d-bddc-9e7907ec3a60)

**Comment by AntoineGautier** [comment]
## Models that fail to simulate with the change

```yml
- model_name: Buildings.DHC.Plants.Combined.Validation.AllElectricCWStorage
  optimica:
    comment:  "Simulation times out"
    simulate: false
- model_name: Buildings.Fluid.HydronicConfigurations.ActiveNetworks.Examples.InjectionTwoWayCheckValve
  openmodelica:
    comment: 'Singular system of equations when both load valves are fully closed but pump is running'
    simulate: false
- model_name: Buildings.Templates.Plants.HeatPumps.Components.Validation.ValvesIsolation
  optimica:
    comment: Possible chattering detected at t = 3.120112e+03 in state event
    simulate: false
```

Simulating these models with Dymola also yields NL solver failures, but the solver can recover from them and the simulation ultimately succeeds.

We can already notice that all these models include one or more instances of `Buildings.Fluid.FixedResistances.CheckValve` and that the NL solver issues disappear when these instances are removed, or even replaced by a fixed resistance.

## `Buildings.DHC.Plants.Combined.Validation.AllElectricCWStorage`

Locally, the simulation succeeds with OCT v1.51.6 (same as in `.travis.yml`) on Ubuntu 22.04 with the attached Python dependencies
[requirements_1.51.6.txt](https://github.com/user-attachments/files/17289339/requirements_1.51.6.txt) that match the requirements from "OPTIMICA Compiler Toolkit Version 1.51.6" Appendix C.

```
Tolerances (relative)    : 1e-06
Simulation interval    : 0.0 - 345600.0 seconds.
Elapsed simulation time: 70.70019977999982 seconds.
```

## `Buildings.Fluid.HydronicConfigurations.ActiveNetworks.Examples.InjectionTwoWayCheckValve`

Locally, the simulation stalls with OMC (v around 60000 s when `loa1.yVal_actual` ~ 0.63 and `con.yVal_actual` ~ 0.59, so not in a situation where the pump work against closed valves (anyway both primary and secondary loops have an end-of-line bypass that prevents the pumps from being dead-headed).

The time of failure matches a local minimum of the check valve ∆p:

<img width="511" alt="image" src="https://github.com/user-attachments/assets/051b5f47-8811-4e29-ab56-08ceeaf696d7">

With the following change in `Buildings.Fluid.FixedResistances.CheckValve`, the simulation succeeds with OMC.

```mo
  // cv = smooth(2, max(0, min(1, a^3*(10+a*(-15+6*a)))));
  cv = Buildings.Utilities.Math.Functions.smoothLimit(a, 0, 1, 1E-4);
```
```
### STATISTICS ###
timer
    0.115013s          reading init.xml
   0.0188655s          reading info.xml
    0.004398s [  0.8%] pre-initialization
   0.0935471s [ 16.6%] initialization
 0.000136875s [  0.0%] steps
   0.0220566s [  3.9%] solver (excl. callbacks)
  0.00309048s [  0.5%] creating output-file
  0.00271059s [  0.5%] event-handling
  0.00505262s [  0.9%] overhead
     0.43359s [ 76.8%] simulation
    0.564582s [100.0%] total
```
